app_id = "app_01j6f7n277e4vrgyr9ey98ps64"

# This is where 'xtp plugin push' expects to find the wasm file after the build script has run.
bin = "target/wasm32-wasi/release/plugin.wasm"
extension_point_id = "ext_01j791ys9dffa89wmaw34z103y"
name = "jq"

[scripts]

  # xtp plugin build runs this script to generate the wasm file
  build = "cargo build --release --target wasm32-wasi"

  # xtp plugin init runs this script to format the plugin code
  format = "cargo fmt"

  # xtp plugin init runs this script before running the format script
  prepare = ""
